### ISSUE TITLE
[Matrix] Color code the table like a heatmap (2)

### ISSUE THREAD

**Issue by chapati23** [chapati23/spin.coffee#10]
As a facility manager, I want to see my biggest energy consumers. In order, to highlight the big one, we use a heatmap color coding using 3 tones of colors (Red, Amber, Yellow)

**Dependencies**
- [x] [Matrix] Display Total cost consumption matrix #95
- [ ] [Matrix] Subheader Component #153

'**Acceptance criteria**
- 0-33% is color coded in yellow #fcea0f
- 34-66% is color coded in amber #f9b211
- 67%-100% is color coded in red #e6332a
- Empty cells are light grey
- Heatmap legend is displayed in the top right corner and displays a gradient from red over amber to yellow

**Tasks Breakdown**
* [ ] Add colors to `theme.js` and global css variables
* [ ] Replace hardcoded values in utility-matrix with `render(value, row, index)` function that dynamically adds classes for color-coding based on its percentage of the total
* [ ] Implement heatmap-gradient in subheader at the top-right

**Resources**
![2016-05-31_1927](http://githuben.intranet.mckinsey.com/download/user/1067/files/c94372b6-2765-11e6-8a6f-73a40251b926)
